# 1. Começando com Numpy

In [ ]:
!python -V

Python 3.7.12


In [ ]:
import numpy as np

# 1.1 Teste de expressoes python numpy

In [ ]:
10 % 2 + 3 // 10

0

In [ ]:
5 * (2 + 3) / 2

12.5

In [ ]:
2 ** 3 * 4

32

# Variaveis e expressoes

In [ ]:
ano_atual, ano_fabricacao, km_total = 2019, 2003, 44410.0
km_media = km_total/(ano_atual - ano_fabricacao)
km_total += km_media
km_total

47185.625

In [ ]:
a = 10
b = 20
c = 'Python e '
d = 'legal'

In [ ]:
a + b

30

In [ ]:
c + d

'Python e legal'

In [ ]:
str(a)

'10'

In [ ]:
c + str(a)

'Python e 10'

In [ ]:
float(a)

10.0

In [ ]:
var = 3.141592
int(var)

3

**Teste Alura:**

In [ ]:
text = 'A quilometragem média do veículo é '
Km = 100000
Ano_atual = 2019
Ano_fabricacao = 1999

In [ ]:
text + str( int( Km / (Ano_atual - Ano_fabricacao) ) ) + ' km'

'A quilometragem média do veículo é 5000 km'

## str.format()

In [ ]:
print('Olá, {}! Este é seu acesso de número {}'.format('Rodrigo', 32))

Olá, Rodrigo! Este é seu acesso de número 32


In [ ]:
print('Olá, {nome}! Este é seu acesso de número {acesso}'.format(nome = 'Rodrigo', acesso = 32))

Olá, Rodrigo! Este é seu acesso de número 32


# f-Strings

In [ ]:
nome = 'Pedro'
acessos = 40

In [ ]:
print(f'Olá, {nome}! Este é seu acesso de número {acessos}')

Olá, Pedro! Este é seu acesso de número 40


#2.0 Listas

In [ ]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios[0]

'Rodas de liga'

In [ ]:
Acessorios[-1]

'Sensor de chuva'

In [ ]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]
Carros = [Carro_1, Carro_2]
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [ ]:
Carros[0][0]

'Jetta Variant'

In [ ]:
Carros[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

# *A[i : j]*

In [ ]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios[2:5]

['Piloto automático', 'Bancos de couro', 'Ar condicionado']

In [ ]:
Acessorios[2:]

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios[:5]


['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

# Exercicios de Seleção lista

In [ ]:
letras = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

letras

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

In [ ]:
letras [:2]

['A', 'B']

In [ ]:
letras [2:5]

['C', 'D', 'E']

In [ ]:
letras [5:]


['F', 'G', 'H']

Segundo exercicio:

In [ ]:
carros = [
    [
        'Jetta Variant',
        'Motor 4.0 Turbo',
        2003,
        False,
        ['Rodas de liga', 'Travas elétricas', 'Piloto automático']
    ],
    [
        'Passat',
        'Motor Diesel',
        1991,
        True,
        ['Central multimídia', 'Teto panorâmico', 'Freios ABS']
    ]
]

In [ ]:
carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático']],
 ['Passat',
  'Motor Diesel',
  1991,
  True,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS']]]

In [ ]:
carros[1][3]

True

In [ ]:
carros[1][4][1]

'Teto panorâmico'

In [ ]:
carros[0][-1]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

## 2.1 Métodos de Listas

# A.sort()

In [ ]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios.sort()
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

# A.append(x)

In [ ]:
Acessorios.append('4 x 4')
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4']

# A.pop(i)

In [ ]:
Acessorios.pop()

'4 x 4'

In [ ]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [ ]:
Acessorios.pop(3)

'Rodas de liga'

In [ ]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [ ]:
Acessorios.append('Travas elétricas')

In [ ]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'Travas elétricas']

In [ ]:
Acessorios.sort() #arrumando o item   que tirei sem querer

In [ ]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'Travas elétricas']

# A.copy()

neste caso A[:] é semelhante ao comando acima.

In [ ]:
Acessorios_2 = Acessorios
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'Travas elétricas']

In [ ]:
Acessorios_2.append('4 x 4')
Acessorios #fazer isso não cria/copia uma lista já existente, apenas declara uma nova váriavel

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'Travas elétricas',
 '4 x 4']

In [ ]:
Acessorios.pop()

'4 x 4'

In [ ]:
Acessorios.pop()

'Travas elétricas'

In [ ]:
Acessorios_2 = Acessorios.copy() #Dessa maneira copiamos/criamos uma nova lista na mémoria que é diferente da primeira
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [ ]:
Acessorios_2.append('4 x 4')
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4']

In [ ]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

Exercicios Metodos de listas

Ex 1:

In [ ]:
Acessorios = [
    'Rodas de liga', 
    'Travas elétricas', 
    'Piloto automático',
    'Bancos de couro',
    'Ar condicionado'
]
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

In [ ]:
Acessorios.append('Airbag')
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Airbag']

In [ ]:
Acessorios.sort()
Acessorios

['Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Travas elétricas']

In [ ]:
Acessorios.pop()

'Travas elétricas'

In [ ]:
Acessorios.append('Vidros elétricos')
Acessorios

['Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Vidros elétricos']

# exercicios

In [ ]:
quadrado = []
for i in range(10):
  quadrado.append(i ** 2)

quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

#ARRAYS

In [ ]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [ ]:
idade = 2019 - anos

In [ ]:
idade

array([16, 28, 29,  0, 13])

In [ ]:
km_media = km / idade

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [ ]:
dados = np.array([km, anos])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados.shape

(2, 5)

In [ ]:
peso = np.array([106.0, 68.5, 75.0])
altura = np.array([1.9, 1.53, 1.75])
IMC = peso / (altura * altura)
IMC

array([29.36288089, 29.26224956, 24.48979592])

In [ ]:
peso = np.array([106.0, 68.5, 75.0])
altura = np.array([1.9, 1.53, 1.75])
IMC = peso / altura ** 2
IMC

array([29.36288089, 29.26224956, 24.48979592])